### ISSUE TITLE
Notifications dropdown backend integration

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4055]
Change existing mock call to the integration with backend
Challenge link: https://www.topcoder.com/challenges/30117693/?type=develop

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari @luizrrodrigues , broadcast notifications are not seen for some users.
eg: TonyJ, Mess, tester1234 etc
We can see broadcast notifications for the following user : dan_developer

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari @luizrrodrigues , for challenge specific notifications, the users do not get the notification when the checkpoint review ends. 
Notifications for challenge spec modification and submission upload is displayed.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari @luizrrodrigues , When the challenge spec for the challenge"30055753" is modified, we can observe the following. this is the registrants list:
<img width="1182" alt="Screenshot 2020-03-11 at 5 06 55 PM" src="https://user-images.githubusercontent.com/58783823/76413060-bd58c600-63ba-11ea-81de-592fc8c1881e.png">

No notification for dan_developer
<img width="1440" alt="Screenshot 2020-03-11 at 5 08 05 PM" src="https://user-images.githubusercontent.com/58783823/76413175-fa24bd00-63ba-11ea-90f4-a299f3395271.png">

Double notification for TonyJ
<img width="1440" alt="Screenshot 2020-03-11 at 5 08 25 PM" src="https://user-images.githubusercontent.com/58783823/76413202-03ae2500-63bb-11ea-9edc-d1e77ffc2d66.png">
Correct notification for Mess
<img width="1440" alt="Screenshot 2020-03-11 at 5 09 53 PM" src="https://user-images.githubusercontent.com/58783823/76413278-27716b00-63bb-11ea-8b01-5f1481106ba4.png">

**Comment by sachin-maheshwari** [comment]
> @sachin-maheshwari @luizrrodrigues , When the challenge spec for the challenge"30055753" is modified, we can observe the following. this is the registrants list:
> <img alt="Screenshot 2020-03-11 at 5 06 55 PM" width="1182" src="https://user-images.githubusercontent.com/58783823/76413060-bd58c600-63ba-11ea-81de-592fc8c1881e.png">
> 
> No notification for dan_developer
> <img alt="Screenshot 2020-03-11 at 5 08 05 PM" width="1440" src="https://user-images.githubusercontent.com/58783823/76413175-fa24bd00-63ba-11ea-90f4-a299f3395271.png">
> 
> Double notification for TonyJ
> <img alt="Screenshot 2020-03-11 at 5 08 25 PM" width="1440" src="https://user-images.githubusercontent.com/58783823/76413202-03ae2500-63bb-11ea-9edc-d1e77ffc2d66.png">
> Correct notification for Mess
> <img alt="Screenshot 2020-03-11 at 5 09 53 PM" width="1440" src="https://user-images.githubusercontent.com/58783823/76413278-27716b00-63bb-11ea-8b01-5f1481106ba4.png">

As checked quickly for dan_developer, no notification issue -  not getting 'dan_devloper' in corresponding challenge api call i.e. https://api.topcoder-dev.com/v4/challenges/30055753/resources

**Comment by luizrrodrigues** [comment]
> Double notification for TonyJ
@SathyaJayabal this coming from backend:

![image](https://user-images.githubusercontent.com/7029641/76427077-a0a49a00-638a-11ea-9f14-0878d8fbc0ed.png)

**Comment by luizrrodrigues** [comment]
> @sachin-maheshwari @luizrrodrigues , broadcast notifications are not seen for some users.
eg: TonyJ, Mess, tester1234 etc
We can see broadcast notifications for the following user : dan_developer

I'm able to see to TonyJ user, can you share login info to:
Mess and tester1234

Thanks

**Comment by luizrrodrigues** [comment]
> For challenge specific notifications, the users do not get the notification when the checkpoint review ends.

@sachin-maheshwari I don't see any notification from `notifications.autopilot.events` yet. Is this the right type to challenge autopilot events right?

**Comment by SathyaJayabal** [comment]
> > @sachin-maheshwari @luizrrodrigues , broadcast notifications are not seen for some users.
> > eg: TonyJ, Mess, tester1234 etc
> > We can see broadcast notifications for the following user : dan_developer
> 
> I'm able to see to TonyJ user, can you share login info to:
> Mess and tester1234
> 
> Thanks

password for both: appirio123

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , we had to remove the notifications for submission uploaded event as per. the below discussion.
https://topcoder.slack.com/archives/CG2J9RH70/p1583878405014700?thread_ts=1583858564.012400&cid=CG2J9RH70

On a submission being uploaded,  the notification is not displayed, but the pink dot is shown when a submission is uploaded.
<img width="1440" alt="Screenshot 2020-03-12 at 9 31 15 AM" src="https://user-images.githubusercontent.com/58783823/76486180-9e9f1180-6444-11ea-81bb-52b990d4e4c7.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Thanks for check.
We need to wait for @sachin-maheshwari remove this from backend return.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Thanks for check. This was fixed.
af2c92680330db0a56f99c2b09d0bff3a2b89516

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal Thanks for check. This was fixed.
> [topcoder-platform/navigation-component@af2c926](https://github.com/topcoder-platform/navigation-component/commit/af2c92680330db0a56f99c2b09d0bff3a2b89516)

Still see it @luizrrodrigues . See video for reference
[sub notif.mov.zip](https://github.com/topcoder-platform/community-app/files/4323165/sub.notif.mov.zip)

@sachin-maheshwari @luizrrodrigues , Marking this as fail until all the above issues are fixed. But let me know if you need any specific scenario tested.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I have fixed the issue when msg isRead but no isSeen. 

Now we need backend update, @sachin-maheshwari we need to remove `submission.notification.create` type from backend return.

**Comment by sachin-maheshwari** [comment]
> > Double notification for TonyJ
> > @SathyaJayabal this coming from backend:
> 
> ![image](https://user-images.githubusercontent.com/7029641/76427077-a0a49a00-638a-11ea-9f14-0878d8fbc0ed.png)
> 
> @sachin-maheshwari

Please check message is same but 'id' is different that mean same message is published twice.

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  Can please summarize the issues which i need to address.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari ,
1. Broadcast notifications not showing up for some users 
eg: TonyJ, Mess, tester1234 etc
We can see broadcast notifications for the following user : dan_developer
2. Checkpoint review end notification is not displayed for all users.
3. Challenge spec modified notification is displaying inconsistently for different users ( https://github.com/topcoder-platform/community-app/issues/4055?email_token=AOAPQT7MLY3JXKBQBDTJMNLRG55P5A5CNFSM4LACB6DKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOPJNCI#issuecomment-597584585)
      a.  No notification for dan_developer - Here you say dan_developer is not returned from the corresponding challenge api call, But the user is shown as registered and also submitted for that challenge. This could be a data integrity issue with the dev data. What do you suggest we do about this case?
      b. double notification for tonyj

**Comment by SathyaJayabal** [comment]
3: a is tracked here #4104 
3:  b. is tracked here #4105

**Comment by sachin-maheshwari** [comment]
1  is tracked here https://github.com/topcoder-platform/tc-notifications/issues/182

**Comment by luizrrodrigues** [comment]
@SathyaJayabal create this one too:

> Now we need backend update, @sachin-maheshwari we need to remove submission.notification.create type from backend return.

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal create this one too:
> 
> > Now we need backend update, @sachin-maheshwari we need to remove submission.notification.create type from backend return.

tracked here #4108

**Comment by SathyaJayabal** [comment]
#2 tracked here #4114

**Comment by SathyaJayabal** [comment]
#4104 
except for this issue everything else works fine. 
I am marking this as pass.

**Comment by SathyaJayabal** [comment]
verified on beta (develop).
Broadcast notifications
Checkpoint review and Checkpoint Screening notifications


Spec modified notification is deferred to release 2.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-30 at 5 53 01 PM" src="https://user-images.githubusercontent.com/58783823/77911951-53dc2100-72af-11ea-8dfe-938a71273a82.png">
