### ISSUE TITLE
Ratings number not updating on member profile

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4130]
Issue: the rating number for Code is not updating after a dev challenge even though the graph updated.

Expected behavior: the rating number should update appropriately after dev challenges as well as the cooresponding graph

To reproduce 
1. Go to: https://www.topcoder.com/members/birdofpreyru/details/?track=DEVELOP&subTrack=CODE
2. see rating in yellow read 1664 but graph reads 1809
3. rating number and graph do not match

**Comment by adroc-tc** [comment]
@Oanh-and-only-Oanh checking in on this issue - is there a date to tackle this issue?

**Comment by Oanh-and-only-Oanh** [comment]
@adroc-tc, we'll try to tackle this next week.

**Comment by skyhit** [comment]
@Oanh-and-only-Oanh , the main reason is the data is retrieved from different backend apis.

1. 1664 is from api call https://api.topcoder.com/v3/members/birdofpreyru/stats
2. while 1809 is getting from https://api.topcoder.com/v3/members/birdofpreyru/stats/history

so here are two solutions.

1. update the UI to use just the last rating of last challenge from #2.
2. we need to research into the v3 member apis.

which do you prefer?

**Comment by Oanh-and-only-Oanh** [comment]
@skyhit,

Please go with solution #1. "update the UI to use just the last rating of last challenge from #2."

**Comment by harshitmehta123** [comment]
Hey @Oanh-and-only-Oanh @skyhit there is a bigger issue here,  I think the loader is not updating stats in Dynamo properly.

Take a look at tourisr

So tourist's rating should be - from (history)
{"challengeId":17900,"challengeName":"SRM 782","date":"2020-03-28T00:00:00.000Z","rating":3751.0,"placement":1,"percentile":99.9552

Howver in stats
DATA_SCIENCE":{"challenges":603,"wins":35,"mostRecentEventName":"SRM 774","mostRecentEventDate":"2020-01-11T00:00:00.000Z","mostRecentSubmission":"2019-12-11T13:00:12.921Z"

`SRM 774 to SRM 782` the stats are not getting updated correctly.

Please check the loaders.
 @adroc-tc

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, can you check to see if this is still an issue in PROD?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this issue is fixed on production
<img width="1424" alt="Screenshot 2020-04-14 at 9 59 38 PM" src="https://user-images.githubusercontent.com/58783823/79249702-49b74680-7e9b-11ea-90d7-66bfd9c755f8.png">

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal @luizrrodrigues this issue is back again in PROD.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh This is FE issue, looks like not getting latest challenge from track.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Like discuss in Slack, after a deeper check, this issue coming from `/v3/members/wleite/stats` API, returned data pointing latest event in March, but in `/v3/members/wleite/stats/history` 

`/stats`: https://api.topcoder.com/v3/members/wleite/stats
![image](https://user-images.githubusercontent.com/7029641/98807292-2fc1f000-23f9-11eb-8320-024996327ff6.png)

`/history`: https://api.topcoder.com/v3/members/wleite/stats/history
![image](https://user-images.githubusercontent.com/7029641/98807308-3486a400-23f9-11eb-8dfc-5b5a391933c5.png)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , ratings have been fixed.
https://topcoder.slack.com/archives/G011L5G6F9U/p1615199152168400
