### ISSUE TITLE
Quartz Energy Geosteering - Formation Interpolation

### ISSUE THREAD

**Issue by infomativearchitect** [topcoder-platform/community-app#605]
https://www.topcoder.com/challenges/30060651/?type=develop

Persistent receipt of error-message: Failed to load challenge.

Browser: Firefox 57.0

**Comment by birdofpreyru** [comment]
Presumably, should work now.

**Comment by infomativearchitect** [comment]
Thank you for the response.

I just tried.  Unfortunately, still not working - I am logged-out and
receive error-page.

Only 2 windows open to TopCoder.
