### ISSUE TITLE
Address update in profile is not being updated in Informix

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#825]
Steps to reproduce:

1. Open the link https://www.topcoder.com/settings/account/ to update the address details.
2. Fill in the details to be updated.
3. Click on Save
4. Open pacts
5. Search handle for which address has been updated

![image](https://user-images.githubusercontent.com/37835397/38895373-858bea48-42ad-11e8-9fb5-8c79d774d09e.png)
![image 1](https://user-images.githubusercontent.com/37835397/38895371-8553d91e-42ad-11e8-971c-7f4b05e528aa.png)

**Comment by birdofpreyru** [comment]
@skyhit looks like your job to do, not directly related to `community-app`

**Comment by RiteshTC** [comment]
@urwithat 
Is this something related to your work ? Can you please confirm.

cc @ajefts

**Comment by ajefts** [comment]
@urwithat Let's chat about this one on the standup.  I think it's something we can tackle in the scope of the profile updates with @ThomasKranitsas

**Comment by RiteshTC** [comment]
@urwithat is there an update on this ticket ?
Apparently, from the issues received, it appears none of the changes made by the user in the community app (Dynamo) is being carried over to the backend.

**Comment by ajefts** [comment]
@cwdcwd @urwithat Can we put some priority on this one for a fix?  It's causing a bunch of issues.  The gist of it is that when someone updates their profile on the site, it is storing the updates in Dynamo but not in Informix...and we use the informix address for things like payments, docusign, etc....

**Comment by cwdcwd** [comment]
@ajefts let me dig in a little. I don't think we rolled any changes forward on that service

**Comment by urwithat** [comment]
@RiteshTC - this should have resolved. @cwdcwd  foudn the issue, there was a logstash service that shoves the dynamo data into informix and elastic search. This had run out of disk and couldn’t update informix. It was running out of disk because it was logging, the fact that it can’t reach elastic search due to credentials missing.

**Comment by urwithat** [comment]
Considering this has been resolved

**Comment by JayaDhaka** [comment]
@cwdcwd I have updated state and country from here https://www.topcoder.com/settings/account/ but this change is not reflecting in PACTS. Please check and fix this.

**Comment by cwdcwd** [comment]
I'm still seeing a failure of logstash to push data into ES. `User: anonymous is not authorized to perform: es:ESHttpPost on resource: topcoder` 
@urwithat can you take a look at this repo, specifically [this conf](https://github.com/appirio-tech/tc-logstash-conf/blob/master/conf/members-es-conf.j2#L188) to see if we need to get that updated to include credentials to connect to the ES API?
